// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using CategoryServices.Data;


#nullable disable

namespace CategoryAPI.Migrations
{
    [DbContext(typeof(CategoryDbContext))]
    [Migration("20251024102916_SeedCategories")]
    partial class SeedCategories
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CategoryModels.Category", b =>
                {
                    b.Property<int>("CategoryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryID"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CategoryID");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryID = 1,
                            CategoryName = "Beverages",
                            Description = "Soft drinks, coffees, teas, beers, and ales"
                        },
                        new
                        {
                            CategoryID = 2,
                            CategoryName = "Condiments",
                            Description = "Sweet and savory sauces, relishes, spreads, and seasonings"
                        },
                        new
                        {
                            CategoryID = 3,
                            CategoryName = "Confections",
                            Description = "Desserts, candies, and sweet breads"
                        },
                        new
                        {
                            CategoryID = 4,
                            CategoryName = "Dairy",
                            Description = "Cheeses"
                        },
                        new
                        {
                            CategoryID = 5,
                            CategoryName = "Grains/Cereals",
                            Description = "Breads, crackers, pasta, and cereal"
                        },
                        new
                        {
                            CategoryID = 6,
                            CategoryName = "Meat/Poultry",
                            Description = "Prepared meats"
                        },
                        new
                        {
                            CategoryID = 7,
                            CategoryName = "Produce",
                            Description = "Dried fruit and bean curd"
                        },
                        new
                        {
                            CategoryID = 8,
                            CategoryName = "Seafood",
                            Description = "Seaweed and fish"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
